/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "Infinity-Army-Tools"
include("Gui", "Core")

pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}