/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
    id("org.openjfx.javafxplugin") version "0.0.10"
    id("net.codersoffortune.infinity.java-conventions")
}


dependencies {
    implementation("net.codersoffortune.infinity:Core:1.0.0-SNAPSHOT")
    implementation("org.openjfx:javafx-controls:15.0.1")
    implementation("org.openjfx:javafx-fxml:15.0.1")
    implementation("org.apache.maven.plugins:maven-shade-plugin:3.2.4")
    implementation("com.akathist.maven.plugins.launch4j:launch4j-maven-plugin:1.7.25")
    implementation(project(":Core"))
}

description = "Gui"

javafx {
    version = "15.0.1"
    modules("javafx.controls", "javafx.fxml")
}
