import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 */


repositories {
    mavenCentral()
}


plugins {
    id("org.openjfx.javafxplugin")
    id("net.codersoffortune.infinity.java-conventions")
    id("edu.sc.seis.launch4j")
    kotlin("jvm")
    kotlin("plugin.serialization")
}


dependencies {
    implementation("org.apache.logging.log4j:log4j-core:2.17.1")
    implementation("org.openjfx:javafx-controls:15.0.1")
    implementation("org.openjfx:javafx-fxml:15.0.1")
    implementation(project(":Core"))
    implementation(kotlin("stdlib-jdk8"))
}

description = "Gui"

javafx {
    version = "15.0.1"
    modules("javafx.controls", "javafx.fxml")
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

launch4j {
    mainClassName = "net.codersoffortune.infinity.gui.Entrypoint"
    outfile = "InfinityArmyTools.exe"
    headerType = "console"
    dontWrapJar = true
    classpath = mutableSetOf("lib/*")
}

val copyRuntimeDeps by tasks.registering(Copy::class) {
    from(configurations.runtimeClasspath)
    into(layout.buildDirectory.dir("launch4j/lib"))
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

val copyGuiJar by tasks.registering(Copy::class) {
    from(tasks.named<Jar>("jar").flatMap { it.archiveFile })
    into(layout.buildDirectory.dir("launch4j"))
}

tasks.named("createExe") {
    dependsOn(copyRuntimeDeps, copyGuiJar)
}

val compileKotlin: KotlinCompile by tasks
compileKotlin.kotlinOptions {
    jvmTarget = "11"
}

val compileTestKotlin: KotlinCompile by tasks
compileTestKotlin.kotlinOptions {
    jvmTarget = "11"
}

tasks.register<JavaExec>("run") {
    mainClass.set("net.codersoffortune.infinity.gui.Entrypoint")
    classpath = sourceSets["main"].runtimeClasspath
    workingDir = rootProject.projectDir
}