
/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    "maven-publish"
    id("net.codersoffortune.infinity.java-conventions")
    kotlin("plugin.serialization") version "1.6.0-RC2"
}

dependencies {
    implementation("org.apache.logging.log4j:log4j-core:2.14.0")
    implementation("org.apache.commons:commons-text:1.9")
    implementation("org.apache.commons:commons-csv:1.8")
    implementation("com.fasterxml.jackson.core:jackson-core:2.11.3")
    implementation("com.fasterxml.jackson.core:jackson-annotations:2.11.3")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.11.3")
    implementation("com.codepoetics:protonpack:1.16")
    implementation("org.codehaus.mojo:exec-maven-plugin:3.0.0")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.1")
}

description = "Core"
